title: Karthick T Sharma
url: "https://karthick47v2.github.io/"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: no

favicon: yes
favicon_location: favicon.ico

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Resume"
    link: "resume.pdf"
  - name: "Projects"
    link: "projects"
  - name: "Services"
    link: "services"
  - name: "Contact"
    link: "contact"
